# 1. Data Cleaning

In [1]:
import pandas as pd
df=pd.read_csv("E:/Project/Project files/Microsoft/Data/new_train_sample.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4758418 entries, 0 to 4758417
Data columns (total 46 columns):
 #   Column              Dtype
---  ------              -----
 0   Unnamed: 0          int64
 1   Id                  int64
 2   OrgId               int64
 3   IncidentId          int64
 4   AlertId             int64
 5   Timestamp           object
 6   DetectorId          int64
 7   AlertTitle          int64
 8   Category            object
 9   MitreTechniques     object
 10  IncidentGrade       object
 11  ActionGrouped       object
 12  ActionGranular      object
 13  EntityType          object
 14  EvidenceRole        object
 15  DeviceId            int64
 16  Sha256              int64
 17  IpAddress           int64
 18  Url                 int64
 19  AccountSid          int64
 20  AccountUpn          int64
 21  AccountObjectId     int64
 22  AccountName         int64
 23  DeviceName          int64
 24  NetworkMessageId    int64
 25  EmailClusterId      float64
 26  RegistryKey         int64
 27  RegistryValueName   int64
 28  RegistryValueData   int64
 29  ApplicationId       int64
 30  ApplicationName     int64
 31  OAuthApplicationId  int64
 32  ThreatFamily        object
 33  FileName            int64
 34  FolderPath          int64
 35  ResourceIdName      int64
 36  ResourceType        object
 37  Roles               object
 38  OSFamily            int64
 39  OSVersion           int64
 40  AntispamDirection   object
 41  SuspicionLevel      object
 42  LastVerdict         object
 43  CountryCode         int64
 44  State               int64
 45  City                int64
dtypes: float64(1), int64(31), object(14)
memory usage: 1.6+ GB

In [2]:
df.shape

(4758418, 46)

In [3]:
df.iloc[:,0:15].head()

,Unnamed: 0,Id,OrgId,IncidentId,AlertId,Timestamp,DetectorId,AlertTitle,Category,MitreTechniques,IncidentGrade,ActionGrouped,ActionGranular,EntityType,EvidenceRole
0,5172780,1709396985476,26,18583,687462,2024-06-06T05:56:47.000Z,31,813,Malware,NaN,BenignPositive,NaN,NaN,File,Related
1,8470561,927712939180,33,5065,3990,2024-06-03T10:45:09.000Z,38,25,Impact,NaN,BenignPositive,NaN,NaN,Machine,Impacted
2,5897583,1090921697002,201,150787,807590,2024-06-13T03:36:40.000Z,419,444,Execution,T1047;T1059;T1053;T1569;T1059.001;T1053.002;T1...,BenignPositive,NaN,NaN,Machine,Impacted
3,3288552,1434519079555,204,108287,28575,2024-06-08T16:54:57.000Z,44,1233,SuspiciousActivity,NaN,TruePositive,NaN,NaN,File,Related
4,4060961,1005022347708,54,528202,1458226,2024-06-09T02:48:01.000Z,102,58829,Exfiltration,NaN,BenignPositive,NaN,NaN,File,Impacted

In [4]:
df.iloc[:,15:30].head()

,DeviceId,Sha256,IpAddress,Url,AccountSid,AccountUpn,AccountObjectId,AccountName,DeviceName,NetworkMessageId,EmailClusterId,RegistryKey,RegistryValueName,RegistryValueData,ApplicationId
0,98799,1296,360606,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251
1,98799,138268,360606,160396,441377,673934,425863,453297,3142,529644,NaN,1631,635,860,2251
2,98799,138268,360606,160396,441377,673934,425863,453297,4181,529644,NaN,1631,635,860,2251
3,98799,138268,360606,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251
4,98799,138268,360606,160396,441377,673934,425863,453297,153085,529644,NaN,1631,635,860,2251

In [5]:
df.iloc[:,30:].head()

,ApplicationName,OAuthApplicationId,ThreatFamily,FileName,FolderPath,ResourceIdName,ResourceType,Roles,OSFamily,OSVersion,AntispamDirection,SuspicionLevel,LastVerdict,CountryCode,State,City
0,3421,881,Casdet,4132,4227,3586,NaN,NaN,5,66,NaN,Suspicious,Malicious,242,1445,10630
1,3421,881,NaN,289573,117668,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630
2,3421,881,NaN,289573,117668,3586,NaN,Destination,5,66,NaN,NaN,NaN,242,1445,10630
3,3421,881,NaN,97007,9177,3586,NaN,NaN,5,66,NaN,Suspicious,Suspicious,242,1445,10630
4,3421,881,NaN,39978,114449,3586,NaN,NaN,5,66,NaN,NaN,NaN,242,1445,10630

In [6]:
#Null Values
Null_columns = df.isnull().sum().reset_index()

null_list = []
for col in Null_columns[Null_columns[0]>0]['index']:
    null_list.append(col)
null_list.remove('IncidentGrade')

#drop null columns
df.drop(columns=null_list,axis=1,inplace=True)

In [7]:
df.columns

Index(['Unnamed: 0', 'Id', 'OrgId', 'IncidentId', 'AlertId', 'Timestamp',
       'DetectorId', 'AlertTitle', 'Category', 'IncidentGrade', 'EntityType',
       'EvidenceRole', 'DeviceId', 'Sha256', 'IpAddress', 'Url', 'AccountSid',
       'AccountUpn', 'AccountObjectId', 'AccountName', 'DeviceName',
       'NetworkMessageId', 'RegistryKey', 'RegistryValueName',
       'RegistryValueData', 'ApplicationId', 'ApplicationName',
       'OAuthApplicationId', 'FileName', 'FolderPath', 'ResourceIdName',
       'OSFamily', 'OSVersion', 'CountryCode', 'State', 'City'],
      dtype='object')

In [8]:
df.drop(columns='Unnamed: 0',axis=1,inplace=True)

In [9]:
#remove duplicates
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(4602224, 35)

In [11]:
#Find unique values
unique_dict={"Col":[],"Unique":[]}
for col in df.columns:
    unique_dict['Col'].append(col)
    unique_dict['Unique'].append(df[col].nunique())
unique_df = pd.DataFrame(unique_dict).sort_values(by=['Unique'],ascending=False)
unique_df

                   Col   Unique
3              AlertId  1163873
4            Timestamp   723647
0                   Id   657035
2           IncidentId   432289
16          AccountUpn   398767
18         AccountName   276656
15          AccountSid   270273
17     AccountObjectId   262205
20    NetworkMessageId   260032
13           IpAddress   195384
27            FileName   142641
14                 Url    85332
19          DeviceName    81164
6           AlertTitle    80121
12              Sha256    73078
28          FolderPath    59652
11            DeviceId    55410
5           DetectorId     7908
34                City     7107
1                OrgId     5607
25     ApplicationName     1610
29      ResourceIdName     1516
33               State     1197
24       ApplicationId     1003
21         RegistryKey      937
23   RegistryValueData      496
26  OAuthApplicationId      416
22   RegistryValueName      401
32         CountryCode      212
31           OSVersion       48
9           EntityType       31
7             Category       20
30            OSFamily        6
8        IncidentGrade        3
10        EvidenceRole        2

In [14]:
df.columns

Index(['Id', 'OrgId', 'IncidentId', 'AlertId', 'Timestamp', 'DetectorId',
       'AlertTitle', 'Category', 'IncidentGrade', 'EntityType', 'EvidenceRole',
       'DeviceId', 'Sha256', 'IpAddress', 'Url', 'AccountSid', 'AccountUpn',
       'AccountObjectId', 'AccountName', 'DeviceName', 'NetworkMessageId',
       'RegistryKey', 'RegistryValueName', 'RegistryValueData',
       'ApplicationId', 'ApplicationName', 'OAuthApplicationId', 'FileName',
       'FolderPath', 'ResourceIdName', 'OSFamily', 'OSVersion', 'CountryCode',
       'State', 'City'],
      dtype='object')

In [12]:
df.iloc[:,0:20].head()

,Id,OrgId,IncidentId,AlertId,Timestamp,DetectorId,AlertTitle,Category,IncidentGrade,EntityType,EvidenceRole,DeviceId,Sha256,IpAddress,Url,AccountSid,AccountUpn,AccountObjectId,AccountName,DeviceName
0,1709396985476,26,18583,687462,2024-06-06T05:56:47.000Z,31,813,Malware,BenignPositive,File,Related,98799,1296,360606,160396,441377,673934,425863,453297,153085
1,927712939180,33,5065,3990,2024-06-03T10:45:09.000Z,38,25,Impact,BenignPositive,Machine,Impacted,98799,138268,360606,160396,441377,673934,425863,453297,3142
2,1090921697002,201,150787,807590,2024-06-13T03:36:40.000Z,419,444,Execution,BenignPositive,Machine,Impacted,98799,138268,360606,160396,441377,673934,425863,453297,4181
3,1434519079555,204,108287,28575,2024-06-08T16:54:57.000Z,44,1233,SuspiciousActivity,TruePositive,File,Related,98799,138268,360606,160396,441377,673934,425863,453297,153085
4,1005022347708,54,528202,1458226,2024-06-09T02:48:01.000Z,102,58829,Exfiltration,BenignPositive,File,Impacted,98799,138268,360606,160396,441377,673934,425863,453297,153085

In [13]:
df.iloc[:,20:].head()

,NetworkMessageId,RegistryKey,RegistryValueName,RegistryValueData,ApplicationId,ApplicationName,OAuthApplicationId,FileName,FolderPath,ResourceIdName,OSFamily,OSVersion,CountryCode,State,City
0,529644,1631,635,860,2251,3421,881,4132,4227,3586,5,66,242,1445,10630
1,529644,1631,635,860,2251,3421,881,289573,117668,3586,5,66,242,1445,10630
2,529644,1631,635,860,2251,3421,881,289573,117668,3586,5,66,242,1445,10630
3,529644,1631,635,860,2251,3421,881,97007,9177,3586,5,66,242,1445,10630
4,529644,1631,635,860,2251,3421,881,39978,114449,3586,5,66,242,1445,10630

In [18]:
# id columns
id_col=[]
for col in df.columns:
    if 'Id' in col:
        id_col.append(col)
print(id_col)

['Id', 'OrgId', 'IncidentId', 'AlertId', 'DetectorId', 'DeviceId', 'AccountObjectId', 'NetworkMessageId', 'ApplicationId', 'OAuthApplicationId', 'ResourceIdName']

In [19]:
#remove id columns
df.drop(columns=id_col,axis=1,inplace=True)

In [28]:
df.drop(columns="AccountSid",inplace=True,axis=1)

In [29]:
df.iloc[:,:12].head()

,Timestamp,AlertTitle,Category,IncidentGrade,EntityType,EvidenceRole,Sha256,IpAddress,Url,AccountUpn,AccountName,DeviceName
0,2024-06-06T05:56:47.000Z,813,Malware,BenignPositive,File,Related,1296,360606,160396,673934,453297,153085
1,2024-06-03T10:45:09.000Z,25,Impact,BenignPositive,Machine,Impacted,138268,360606,160396,673934,453297,3142
2,2024-06-13T03:36:40.000Z,444,Execution,BenignPositive,Machine,Impacted,138268,360606,160396,673934,453297,4181
3,2024-06-08T16:54:57.000Z,1233,SuspiciousActivity,TruePositive,File,Related,138268,360606,160396,673934,453297,153085
4,2024-06-09T02:48:01.000Z,58829,Exfiltration,BenignPositive,File,Impacted,138268,360606,160396,673934,453297,153085

In [30]:
df.iloc[:,12:].head()

,RegistryKey,RegistryValueName,RegistryValueData,ApplicationName,FileName,FolderPath,OSFamily,OSVersion,CountryCode,State,City
0,1631,635,860,3421,4132,4227,5,66,242,1445,10630
1,1631,635,860,3421,289573,117668,5,66,242,1445,10630
2,1631,635,860,3421,289573,117668,5,66,242,1445,10630
3,1631,635,860,3421,97007,9177,5,66,242,1445,10630
4,1631,635,860,3421,39978,114449,5,66,242,1445,10630

In [31]:
#Find unique values
unique_dict={"Col":[],"Unique":[]}
for col in df.columns:
    unique_dict['Col'].append(col)
    unique_dict['Unique'].append(df[col].nunique())
unique_df = pd.DataFrame(unique_dict).sort_values(by=['Unique'],ascending=False)
unique_df

                  Col  Unique
0           Timestamp  723647
9          AccountUpn  398767
10        AccountName  276656
7           IpAddress  195384
16           FileName  142641
8                 Url   85332
11         DeviceName   81164
1          AlertTitle   80121
6              Sha256   73078
17         FolderPath   59652
22               City    7107
15    ApplicationName    1610
21              State    1197
12        RegistryKey     937
14  RegistryValueData     496
13  RegistryValueName     401
20        CountryCode     212
19          OSVersion      48
4          EntityType      31
2            Category      20
18           OSFamily       6
3       IncidentGrade       3
5        EvidenceRole       2

In [42]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])

In [43]:
df['Year']=df['Timestamp'].dt.year
df['Month']=df['Timestamp'].dt.month
df['Day']=df['Timestamp'].dt.day

In [44]:
#Timestamp
df.drop(columns="Timestamp",axis=1,inplace=True)

In [46]:
len(df.columns)

25

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4602224 entries, 0 to 4758417
Data columns (total 25 columns):
 #   Column             Dtype
---  ------             -----
 0   AlertTitle         int64
 1   Category           object
 2   IncidentGrade      object
 3   EntityType         object
 4   EvidenceRole       object
 5   Sha256             int64
 6   IpAddress          int64
 7   Url                int64
 8   AccountUpn         int64
 9   AccountName        int64
 10  DeviceName         int64
 11  RegistryKey        int64
 12  RegistryValueName  int64
 13  RegistryValueData  int64
 14  ApplicationName    int64
 15  FileName           int64
 16  FolderPath         int64
 17  OSFamily           int64
 18  OSVersion          int64
 19  CountryCode        int64
 20  State              int64
 21  City               int64
 22  Year               int32
 23  Month              int32
 24  Day                int32
dtypes: int32(3), int64(18), object(4)
memory usage: 860.2+ MB

In [48]:
#export cleaned data
df.to_csv('cleaned_df.csv')